### ISSUE TITLE
Even if my webfeed (xml) is empty, the template is shown

### ISSUE THREAD

**Issue by rapha7** [onsigntv/apps#1]
When my .xml doesn't has any value, the app is shown with blank values, how to make it be hidden in this cases?

Thank you,

**Comment by edufelipe** [comment]
Hi there!

There are two possible ways of doing this, and both work at the campaign level, meaning it will skip the entire campaign when the XML is empty, not just the app.

If that works for you it is possible to call [`signage.stopCurrentCampaign()`](https://github.com/onsigntv/apps/blob/master/docs/JSBRIDGE.md#signagestopcurrentcampaign) on the app. This call currently works only on Android players and it will make the campaign to be skipped. Please don't forget to use a `try {} catch (e) {}` around the call, so your app can also be used on players that does not support that feature.

The other choice is using the [`{% error %}` template tag](https://github.com/onsigntv/apps/blob/master/docs/USERCONF.md#user-data-validation). This will also make the whole campaign to be skipped and it works on all players. Please mind that using this method will generate system warnings for users of this app in the future.

**Comment by rapha7** [comment]
Thank u too much about the fast response.

I ve been trying these options, but infortunately it doesnt handle my problem :/

Because {% error %} template tag just works with values passed by end-user, right? I'd need to know if the fetch is empty with jinja2 and then to stop campaign if yes.

There is some function or tag to access the fetch result on jinja2?

I m fetching this way: {{fetch_feed(web_xml_url)}}
