### ISSUE TITLE
Button Import App is missing

### ISSUE THREAD

**Issue by ronaldux** [onsigntv/apps#2]
At content section over the .html file the option to import as app is missing, I don't know if is a bug or was remove, I try with the samples and I can't add to my apps and configure.

![image](https://user-images.githubusercontent.com/57640898/105196593-8dba3480-5b1a-11eb-921c-b0c7e5090c6c.png)

**Comment by edufelipe** [comment]
Hi @ronaldux!

Thanks for your interest in developing apps for our platform!

That functionality needs to be manually enabled before being used.

Please send an email to <support@onsign.tv> asking them to enable App Development for you. Mind that your email must come from the same address you are using to login on OnSign TV.

Thanks again and have a nice day!
