### ISSUE TITLE
Datafeed: not showing options

### ISSUE THREAD

**Issue by diegobonagurio** [onsigntv/apps#4]
Hello!
I'm testing using a data feed as shown in the file [https://github.com/onsigntv/apps/blob/master/docs/DATAFEED.md](DATAFEED.md) , but nothing appears on the web for me to select the file.

Any idea what it could be? 

<img width="798" alt="Screen Shot 2023-07-06 at 10 20 25" src="https://github.com/onsigntv/apps/assets/56571038/e03e6019-3350-44c0-b2f8-359b0b562e8c">

<img width="923" alt="Screen Shot 2023-07-06 at 10 31 27" src="https://github.com/onsigntv/apps/assets/56571038/b3a4a3d5-f840-4d70-b926-e7c98d6daa00">

**Comment by edufelipe** [comment]
@diegobonagurio you are using the [app-simulator](https://github.com/onsigntv/app-simulator), correct?

If that's the case, the data in the app simulator is random. At the moment we don't have a way of entering pre-defined data, but we are working on it.

In the mean time, if you load this into our platform at https://app.onsign.tv it will let you select a data feed of your own.

**Comment by diegobonagurio** [comment]
Thanks about the fast response @edufelipe 

Yes, I'm using the app-simulador...
