### ISSUE TITLE
Data Feed Loading with limit

### ISSUE THREAD

**Issue by diegobonagurio** [onsigntv/apps#5]
I have a question regarding the data feed on the signage platform.

When selecting a feed and loading it to my app it always returns loading with 5 items

<img width="562" alt="Screen Shot 2023-08-03 at 21 27 03" src="https://github.com/onsigntv/apps/assets/56571038/5d3836be-22ee-4f34-9ab6-7c4b07831421">

This console.log I added right on feed loading, Note that there are only 5 items and in this table there are 21 rows

<img width="368" alt="Screen Shot 2023-08-03 at 19 31 47" src="https://github.com/onsigntv/apps/assets/56571038/f299f31a-43ae-4bf9-9349-38dd2d8ed4d4">

This console.log below shows the loading of Feed data in APP SIMULATOR. By inserting the number of lines I want it returns the 20 items in the "source"
<img width="453" alt="Screen Shot 2023-08-03 at 21 33 07" src="https://github.com/onsigntv/apps/assets/56571038/930112fa-199b-440b-abf0-4c2a15fb4915">

I believe that the signage platform has some limit when bringing data that always returns 5 items, could you give me any suggestions?

**Comment by edufelipe** [comment]
Hi there!

The current Data Feed limit is 3000 rows.

What might be happening is the app marked the "description" field as being required so we filter for rows that actually have a value on that field.

Please send a message to support@onsign.tv with the email of the account you are using and the name of the app you are trying to configure so we can further help you.

Thanks!
